# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://pynash.org
title: PyNash
header-img: img/home-bg.jpg
subtitle: Nashville Python User Group.
author: Multiple
simple_search: http://google.com/search
description: "PyNash is Nashville's local Python User Group."
twitter_username: pynash
github_username: pynashorg
base_url: ./

source:      .
destination: ./_site
plugins:     ./_plugins
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["README.md"]
